=== liningtonlab/npmrd_curator/jsonschema/compoundrecord.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/schemas/compoundrecord.json",
  "$comment": "Draft 02 - definining properties of objects. Requires additional specficitions of required fields.",
  "title": "Compound Record for NP-MRD consortium",
  "description": "A comprehensive data record for the NP-MRD consortium including extended analytical data records.",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "smiles": { "type": "string" },
    "origin_doi": {
      "type": "string",
      "pattern": "^10.\\d{4,9}/[-._;()/:A-Za-z0-9]+$"
    },
    "origin_type": { "type": "string" },
    "origin_genus": { "type": "string" },
    "origin_species": { "type": "string" },
    "optical_rotation": {
      "type": "object",
      "properties": {
        "temperature": { "type": "number" },
        "reference": { "type": "string" },
        "value": { "type": "number" },
        "concentration": { "type": "number" },
        "solvent": { "type": "string" }
      },
      "required": []
    },
    "uv_spectroscopy": {
      "type": "object",
      "properties": {
        "solvent": { "type": "string" },
        "units": { "type": "string" },
        "spectrum": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "wavelength": { "type": "number" },
              "absorptivity": { "type": "number" }
            }
          }
        }
      },
      "required": []
    },
    "ir_spectroscopy": {
      "type": "object",
      "solvent": { "type": "string" },
      "units": { "type": "string" },
      "spectrum": {
        "type": "array",
        "items": { "type": "number" }
      },
      "required": []
    },
    "h_nmr": {
      "type": "object",
      "properties": {
        "solvent": { "type": "string" },
        "temperature": { "type": "number" },
        "reference": { "type": "string" },
        "spectrum": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "shift": { "type": "number" },
              "integration": { "type": "number" },
              "multiplicty": { "type": "string" },
              "coupling": { "type": "array", "items": { "type": "number" } },
              "atom_index": { "type": "string" },
              "rdkit_index": { "type": "string" }
            },
            "required": []
          }
        },
        "ambiguous": { "type": "array", "items": { "type": "string" } }
      },
      "required": []
    },
    "c_nmr": {
      "type": "object",
      "properties": {
        "solvent": { "type": "string" },
        "temperature": { "type": "number" },
        "reference": { "type": "string" },
        "spectrum": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "shift": { "type": "number" },
              "atom_index": { "type": "string" },
              "rdkit_index": { "type": "string" }
            },
            "required": []
          }
        },
        "ambiguous": { "type": "array", "items": { "type": "string" } }
      },
      "required": []
    }
  },
  "required": []
}

=== liningtonlab/npmrd_curator/jsonschema/compoundrecord-example01.json
{
  "name": "Compound A",
  "smiles": "CC1=C(OC)C=C(C(O)=O)C=C1OC",
  "origin_type": "Bacteria",
  "origin_genus": "Streptomyces",
  "origin_species": "sp.",
  "origin_doi": "10.0000/example-doi",
  "optical_rotation": {
    "temperature": 27,
    "reference": "D",
    "value": -177.7,
    "concentration": 1.02,
    "solvent": "CHCl3"
  },
  "uv_spectroscopy": {
    "solvent": "CH3OH",
    "units": "nm",
    "spectrum": [
      {
        "wavelength": 210,
        "absorptivity": 3.33
      },
      {
        "wavelength": 242,
        "absorptivity": 3.02
      },
      {
        "wavelength": 288,
        "absorptivity": 2.21
      },
      {
        "wavelength": 421,
        "absorptivity": 3.16
      }
    ]
  },
  "ir_spectroscopy": {
    "solvent": "KBr, thin film",
    "units": "cm-1",
    "spectrum": [3017, 2953, 2855, 2192, 1512, 1360, 1082, 887]
  },
  "h_nmr": {
    "solvent": "DMSO-d6",
    "temperature": 25,
    "reference": "TMS",
    "frequency": 400,
    "spectrum": [
      {
        "shift": 8.78,
        "integration": 3,
        "multiplicity": "s",
        "coupling": []
      },
      {
        "shift": 7.15,
        "integration": 1,
        "multiplicity": "d",
        "coupling": [8.2]
      }
    ],
    "ambiguous": ["6âˆ’3 (br s, 5H, NH and NH2)"]
  },
  "c_nmr": {
    "solvent": "DMSO-d6",
    "temperature": 25,
    "reference": "TMS",
    "frequency": 400,
    "spectrum": [
      { "shift": 175.4 },
      { "shift": 156.5 },
      { "shift": 147.4 },
      { "shift": 110.5 },
      { "shift": 52.3 },
      { "shift": 28.8 },
      { "shift": 28.4 }
    ],
    "ambiguous": []
  }
}
